<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>Sprak</string>
	</array>
	<key>name</key>
	<string>Sublime Sprak Syntax</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.sprak</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Comment</string>
			<key>match</key>
			<string>(#).*</string>
			<key>name</key>
			<string>comment.line.sprak</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keyword</string>
			<key>match</key>
			<string>\b((end )?if|(end )?select|(resume )?next|case|end|void|close|do|else|for|gosub|goto|loop|on|open|return|then|to|until|while)\b</string>
			<key>name</key>
			<string>keyword.control.sprak</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Operator</string>
			<key>match</key>
			<string>(\+|=|&lt;|&gt;|&lt;&gt;|AND|OR)</string>
			<key>name</key>
			<string>keyword.operator.sprak</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Function</string>
			<key>match</key>
			<string>\b(OnHack|OnIntruder|Count|Range|GetIndexes|Remove|RemoveAll|HasIndex|Append|Type|Round|Int|Mod|Info|Random|GetUser|Name|Time|Width|Height|GetHour|GetMinute|Sleep|Quit|CharToInt|IntToChar|ClearText|Print|Say|PlaySound|Pitch|Sin|Cos|PrintS|Input|Line|Text|Rect|DisplayGraphics|Color|Repeat|HSVtoRGB|RGBToHSV|Lines|GetConnections|Slurp|Connect|DisconnectAll|StringContains|MovePerson|ZapPerson|RestoreCode|Broadcast|IsKeyPressed|HasFloppy|LoadData|ClearData|SaveData|BootFromFloppy|SetMhz|EnableAPI|SetMaxTime|Speed|Charisma|Smelliness|Sleepiness|Drunkenness|Drink|Corruption|IsUser|GetRoom|RemoteFunctionCall|Trippy|TurnLeft|TurnRight|FastForward|Move|QuickBoost)\b</string>
			<key>name</key>
			<string>support.function.sprak</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Numeric</string>
			<key>match</key>
			<string>\b(\d(\.\d)?)+</string>
			<key>name</key>
			<string>constant.numeric.sprak</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Global</string>
			<key>match</key>
			<string>\b\w+\$</string>
			<key>name</key>
			<string>constant.global.sprak</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.sprak</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>SUB</string>
			<key>match</key>
			<string>^(\w+):</string>
			<key>name</key>
			<string>meta.function.sprak</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Brace, round</string>
			<key>match</key>
			<string>[\(\)]</string>
			<key>name</key>
			<string>meta.brace.round.sprak</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Brace, curly</string>
			<key>match</key>
			<string>[\{\}]</string>
			<key>name</key>
			<string>meta.brace.curly.sprak</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\w+\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.array.sprak</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Array</string>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.array.sprak</string>
				</dict>
			</dict>
			<key>name</key>
			<string>other.array.sprak</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(")</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.sprak</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>String, double-quoted</string>
			<key>end</key>
			<string>(")</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.sprak</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.sprak</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Escaped double-quote inside double-quoted string</string>
					<key>match</key>
					<string>(\\")</string>
					<key>name</key>
					<string>constant.character.escape.sprak</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Single quote inside double-quoted string</string>
					<key>match</key>
					<string>(')</string>
					<key>name</key>
					<string>other.sprak</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.sprak</string>
	<key>uuid</key>
	<string>2e4fc05e-56be-4036-9f17-8a721250c786</string>
</dict>
</plist>
